---
- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/auth?/github
  value:
    enabled: true
    allow_sign_up: true
    api_url: "https://api.github.com/user"
    token_url: "https://github.com/login/oauth/access_token"
    auth_url: "https://github.com/login/oauth/authorize"
    client_id: "((grafana_github_user))"
    client_secret: "((grafana_github_password))"
    scopes: "user:email,read:org"