- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=kube_state_metrics_exporter/properties?/env?
  value:
    http_proxy: ((http_proxy))
    https_proxy: ((https_proxy))
    no_proxy: ((no_proxy))

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/scrape_configs/job_name=kubernetes_nodes/proxy_url?
  value: ((http_proxy))

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/scrape_configs/job_name=kubernetes_apiservers/proxy_url?
  value: ((http_proxy))
