- type: replace
  path: /instance_groups/name=firehose/jobs/name=firehose_exporter/properties?/env?
  value:
    http_proxy: ((http_proxy))
    https_proxy: ((https_proxy))
    no_proxy: ((no_proxy))
