---
name: minio

releases:
- name: minio
  version: "2019-03-20T22-38-47Z"
  url: "https://bosh.io/d/github.com/minio/minio-boshrelease?v=2019-03-20T22-38-47Z"

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

variables:
- name: minio_accesskey
  type: password
- name: minio_secretkey
  type: password

instance_groups:
- name: minio
  azs: [z2]
  instances: 1
  jobs:
  - name: minio-server
    release: minio
    templates:
    - name: minio-server
    provides:
      minio-server: {as: minio-link}
    properties:
      credential:
        accesskey: ((minio_accesskey))
        secretkey: ((minio_secretkey))
      port: 9000
  networks:
  - name: default
  vm_type: default
  persistent_disk_type: 100GB
  stemcell: default

- name: tests
  azs: [z1]
  instances: 1
  lifecycle: errand
  post_deploy: true
  jobs:
  - name: smoke-tests
    release: minio
    templates:
    - name: smoke-tests
    consumes:
      minio: {from: minio-link}
  networks:
  - name: default
  vm_type: default
  persistent_disk_type: default
  stemcell: default

update:
  canaries: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  max_in_flight: 1