name: postgres

update:
  canaries: 1
  canary_watch_time: 30000-600000
  max_in_flight: 1
  serial: true
  update_watch_time: 5000-600000

releases:
- name: postgres
  version: 36
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: postgres
  instances: 1
  stemcell: default
  networks:
  - name: default
    static_ips: [172.16.6.16]
  azs:
  - z2
  vm_type: small
  persistent_disk_type: 10GB
  jobs:
  - name: postgres
    release: postgres
    provides:
      postgres: {as: postgres-database}
    properties:
      databases:
        databases:
        - name: atc
        - name: grafana
        - name: concourse
        - name: vault
        roles:
        - name: pgadmin
          password: ((pgadmin_database_password))
          permissions:
          - "CONNECTION LIMIT 50"
        - name: concourse
          password: ((concourse_database_password))
        - name: grafana
          password: ((grafana_database_password))
        - name: vault
          password: ((vault_database_password))

variables:
- name: pgadmin_database_password
  type: password
- name: concourse_database_password
  type: password
- name: grafana_database_password
  type: password
- name: vault_database_password
  type: password