kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ci-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/vsphere-volume
parameters:
  diskformat: zeroedthick