groups:
  - name: ssl
    rules:
      - alert: ProbeSSLCertExpiryWarning
        expr: avg(probe_ssl_earliest_cert_expiry) by(instance) - time() < <%= p('probe_alerts.cert_expiry_warning.threshold') %>
        for: <%= p('probe_alerts.cert_expiry_warning.evaluation_time') %>
        labels:
          service: probe
          severity: warning
        annotations:
          summary: "Endpoint `{{$labels.instance}}` SSL certificate will expire in {{humanizeDuration $value}}"
          description: "The SSL certificate at endpoint `{{$labels.instance}}` will expire in {{humanizeDuration $value}}"

      - alert: ProbeSSLCertExpiryCritical
        expr: avg(probe_ssl_earliest_cert_expiry) by(instance) - time() < <%= p('probe_alerts.cert_expiry_critical.threshold') %>
        for: <%= p('probe_alerts.cert_expiry_critical.evaluation_time') %>
        labels:
          service: probe
          severity: critical
        annotations:
          summary: "Endpoint `{{$labels.instance}}` SSL certificate will expire in {{humanizeDuration $value}}"
          description: "The SSL certificate at endpoint `{{$labels.instance}}` will expire in {{humanizeDuration $value}}"
