resource_types:
- name: bosh-deploy
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

resources:
- name: homelab-git
  type: git
  source:
    uri: https://github.com/nthomson-pivotal/homelab.git
    branch: master
    paths:
    - bosh/prometheus/*
- name: bosh-deployment
  type: bosh-deploy
  source:
    skip_check: true
    target: https://172.16.6.6:25555
    client: admin
    client_secret: ((director/admin_password))
    ca_cert: ((director/director_ssl.ca))
    deployment: prometheus

jobs:
- name: deploy
  plan:
  - get: homelab-git
    trigger: true
  - put: bosh-deployment
    params:
      manifest: homelab-git/bosh/prometheus/prometheus-boshrelease-24.1.0/manifests/prometheus.yml
      ops_files:
      - homelab-git/bosh/prometheus/prometheus-boshrelease-24.1.0/manifests/operators/monitor-bosh.yml
      - homelab-git/bosh/prometheus/prometheus-boshrelease-24.1.0/manifests/operators/enable-bosh-uaa.yml
      - homelab-git/bosh/prometheus/prometheus-boshrelease-24.1.0/manifests/operators/monitor-concourse.yml
      - homelab-git/bosh/prometheus/operations/external-postgres.yml
      - homelab-git/bosh/prometheus/operations/no-nginx.yml
      vars_files: 
      - homelab-git/bosh/prometheus/vars.yml