postgres_host: 172.16.6.16
postgres_grafana_password: ((/bosh-lab/postgres/grafana_database_password))

bosh_url: 'https://172.16.6.6:25555'
bosh_ca_cert: ((/concourse/main/director/director_ssl.ca))
uaa_bosh_exporter_client_secret: ((/concourse/main/director/uaa_bosh_exporter_client_secret))
metrics_environment: lab

postgres_datasource_name: postgresql://grafana:((/bosh-lab/postgres/grafana_database_password))@172.16.6.16:5432/?sslmode=disable

vault_address: vault.lab.paasify.org

probe_endpoints: [
  https://concourse.lab.paasify.org,
  https://vault.lab.paasify.org/v1/sys/health,
  https://minio.lab.paasify.org/minio/health/live
]

skip_ssl_verify: false