- type: replace
  path: /instance_groups/name=alertmanager/jobs/name=alertmanager/properties/alertmanager/receivers/name=default/pushover_configs?/-
  value:
    user_key: "((alertmanager_pushover_user_key))"
    token: "((alertmanager_pushover_token))"
