# This file assumes bosh_exporter based Service Discovery is being used: ./monitor-bosh.yml

# Exporter jobs
- type: replace
  path: /instance_groups/name=prometheus2/jobs/-
  value:
    name: redis_exporter
    release: prometheus
    properties:
      redis_exporter:
        redis:
          address: "((redis_address))"

# Prometheus Alerts
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=redis_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/redis_alerts/*.alerts.yml

# Grafana Dashboards
- type: replace
  path: /instance_groups/name=grafana/jobs/name=redis_dashboards?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/prometheus/dashboard_folders/name=Redis?/files/-
  value: /var/vcap/jobs/redis_dashboards/*.json
