# Apply ./bosh/add-credhub-exporter-uaa-clients.yml to your bosh-deployment

# Exporter jobs
- type: replace
  path: /instance_groups/name=prometheus2/jobs/-
  value:
    name: credhub_exporter
    release: prometheus
    properties:
      credhub_exporter:
        credhub:
          api_url: ((credhub_url))
          client_id: credhub_exporter
          client_secret: "((uaa_credhub_exporter_client_secret))"
          ca_certs: ((credhub_ca.ca))
        metrics:
          deployment: ((credhub_deployment_name))
          environment: "((metrics_environment))"
        skip_ssl_verify: ((skip_ssl_verify))
        filters:
          generic-certificates:
            - "/static/.*"

# Prometheus Alerts
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=credhub_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/credhub_alerts/*.alerts.yml
