groups:
  - name: pods
    rules:
      - alert: KubernetesPodNotRunning
        expr: kube_pod_status_phase{phase!="Running"} == 1
        for: <%= p('kubernetes_alerts.pod_not_running.evaluation_time') %>
        labels:
          service: kubernetes
          severity: warning
        annotations:
          summary: "Kubernetes Pod `{{$labels.namespace}}/{{$labels.pod}}` is in state `{{$labels.phase}}`"
          description: "Kubernetes Pod `{{$labels.namespace}}/{{$labels.pod}}` not `Running` for more than <%= p('kubernetes_alerts.pod_not_running.evaluation_time') %>"
