name: vault

instance_groups:
- name: vault
  instances: 1
  vm_type: default
  stemcell: xenial
  azs: [z2]
  networks: [{name: default}]
  persistent_disk: 10240

  jobs:
  - name: vault
    release: vault
    properties:
      vault:
        config: |
          ui = true
          storage "postgresql" {
            connection_url = "postgres://vault:((postgres_password))@((postgres_host)):5432/vault?sslmode=disable"
          }
          listener "tcp" {
            address = "0.0.0.0:8200"
            tls_cert_file = "/var/vcap/jobs/vault/tls/vault/cert.pem"
            tls_key_file  = "/var/vcap/jobs/vault/tls/vault/key.pem"
            tls_min_version = "tls12"
          }
          seal "awskms" {
            region = "((aws_region))"
            access_key = "((/shared/aws/vault-kms/access-key))"
            secret_key = "((/shared/aws/vault-kms/secret-key))"
            kms_key_id = "((aws_kms_id))"
          }
      tls:
        - name: vault
          cert: ((vault-tls.certificate))((vault-ca.certificate))
          key: ((vault-tls.private_key))
update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 1
  serial: true
  update_watch_time: 1000-60000

variables:
- name: vault-ca
  type: certificate
  options:
    is_ca: true
    common_name: vaultCA
- name: vault-tls
  type: certificate
  options:
    ca: vault-ca
    common_name: vault
    extended_key_usage:
    - client_auth
    - server_auth
    alternative_names:
    - 127.0.0.1
    - "*.vault.default.vault.bosh"
    - "vault.lab.paasify.org"

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: latest

releases:
- name: vault
  version: 1.1.3
  url: https://github.com/cloudfoundry-community/vault-boshrelease/releases/download/v1.1.3/vault-1.1.3.tgz
  sha1: f345914ee17160524595ee92be7d324b52676916